# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecbd33079bc604eb3a8d0c86661b3ce57313ce6bb0ef41ac935513fbcadea394b06857a4741427dbcd96a2213a610eb42a68938e3b2abbe3c05304e0d54a1e13

test:
  secret_key_base: b23860053d4a1ff2d4b2eb8cc6036cc4e93258ca6f0611a24b5c579275cba9992f4e0ed995030b0aa83f8709c839bf90ff369a757d2f5de8535b3769fd884249

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
